#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

apt update
apt install -y nginx
service nginx start
sed -i 's/^\(\s*listen\s*\)80/\180/' /etc/nginx/sites-available/default
service nginx restart
