#!/usr/bin/env bash
# Displays its own PID.

echo $$
..........................

vi 1-list_your_processes

#!/usr/bin/env bash
# Displays a list of currently running processes.
# Shows all processes, for all users, including those
# which might not have a TTY.

ps -auxf
