#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
nginx -g 'daemon off;'
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
